### ISSUE TITLE
Document clearly in the README that the PostgreSQL DB folder should be mounted from the outside

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-prerequisites#56] opened 2022-07-29 08:23 UTC
By default, what happens? It's in the container layers? Does it mean that it's deleted at container restart?

Also, document this in the important images starting from this, e.g. aiida-core-base.
If not done, the DB is orders of magnitude slower than it could be (resulting in a bad experience for the users).

Louis Beal, can you please comment on your use case?

**Comment by csadorf** [comment] 2022-07-29 10:22
The PostgreSQL database folder is inside the user's home directory. That is – like any other directory – part of the container unless you mount it externally. Why would that be any slower compared to a dedicated volume?

Further, I don't think that any user should use this particular image directly. If anything, users should either use the aiida-core image, or likely a better choice, use the aiidalab image. When starting aiidalab with [aiidalab-launch](https://aiidalab.readthedocs.io/en/latest/usage/index.html#aiidalab-launch), we automatically create a dedicated volume for the user's home directory, which means that data is automatically persisted.

That said, I am still a bit confused at your suggestion. When using docker, data is always only stored over the lifetime of the container unless one creates a volume. This is also clearly documented [here](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/run_docker.html#intro-get-started-docker): 

> All data stored in a container will persist only over the lifetime of that particular container unless you use volumes (see instructions below).

**Comment by ljbeal** [comment] 2022-07-29 10:48
Hi Giovanni, 

Thanks for opening this, it would be great to narrow down the cause of the slowdown I've been experiencing! Our use-case for the container is simply one to ensure constant connectivity with the machines which run the Equation of State calculations.

Since I am working from home almost all the time, I require a VPN connection to be able to run jobs on the machines, however we discovered that the connection seems to have a time limt to it. This means that very frequently I would submit a batch of systems before logging off in the evening and the VPN would disconnect at some point in the night, leaving jobs in a hung state. While aiida would recover from this is most cases, it still took a long time for the daemons to work through all the tasks that had piled up.

To circumvent this situation, a machine was selected on site which we could VPN into and run the common-workflows there. So the [machine/remote] chain changed from

[localhost] -> VPN -> [calculation remote]
to
[localhost] -> VPN -> [onsite machine] -> [calculation remote]

A container was used for this "onsite" machine, partially because it would ensure I had root access if it was required, and partially as this is also the setup used by Augustin previously.

The container in question was initialised with a command similar to the following:
`docker run -ti  -v /home/beal/acwf:/acwf -v /home/beal/.ssh:/.ssh:ro -p 8890:8888 aiidalab/aiidalab-docker-stack`
Something simple to get a running container with the correct aiida-core version. There was a few parallel issues at the time, and the priority was to get something _working_. The basic neccessities were a folder through which to transfer data (`/acwf` in the container, and a read only one for ssh keys)

I shall dump what info I can gather below, don't hesitate to ask if you require more info!

Here is the output of `docker inspect {CONTAINER}`:
[docker_inspect.txt](https://github.com/aiidateam/aiida-prerequisites/files/9218320/docker_inspect.txt)

You were correct with the assumption of the data directory, see the output as follows;
```
SHOW data_directory;
     data_directory
-------------------------
 /home/aiida/.postgresql
```

Which could indeed be the reason why the aiida seems slow to access the database for me.

As the connected folder is within the root directory of the container, the default locations which aiida uses don't fall within, so are entirely within the container itself. I don't believe you can mount a folder to a running (or even stopped?) container, but I'm hesitant to begin playing with containers and services as you are correct, if the container is removed, we lose all the data. Perhaps it's best to wait until the data is to the point where it's as good as we can get it before we begin this testing?

Cheers,
Louis

**Comment by giovannipizzi** [comment] 2022-08-02 13:21
> The PostgreSQL database folder is inside the user's home directory. That is – like any other directory – part of the container unless you mount it externally. Why would that be any slower compared to a dedicated volume?

As far as I understand, the default container uses an overlay filesystem with copy-on-write, that can be thus slow for IO intensive operations (I don't have benchmarks, but I remember at least one case where not mounting/using a volume was making a big difference). I'm not sure of the overheads of bind mounts and/or volumes (that seem to be also host-OS specific from a quick google search).

> When using docker, data is always only stored over the lifetime of the container unless one creates a volume

Indeed - I am a bit worried that not using a volume or mounting from the outside, will risk that users without a technical full understanding of how docker works risk to destroy the container to e.g. update some code version, losing their data.

> Further, I don't think that any user should use this particular image directly

Can you please add, then, a clear message in the readme so people cannot miss it, and suggest what to use instead?

> I'm hesitant to begin playing with containers and services as you are correct, if the container is removed, we lose all the data.

Indeed. However, to avoid data loss risks, the next time you can stop the AiiDA daemon, maybe do a full backup of the home inside the container (e.g. even simply with rsync or something similar), to avoid to lose everything by mistake.

**Comment by yakutovicha** [comment] 2022-08-02 15:18
> By default, what happens? It's in the container layers?

To the best of my knowledge, there is no such thing as a "default mount". It is always up to the user whether they want to mount any folder inside the container.

>  Does it mean that it's deleted at container restart?

A container can be stopped and restarted - the changes will remain (unless the container was deleted explicitly). However, restarting the image will result in a creation of a new container, which always gives an impression that the data are gone.

> Also, document this in the important images starting from this, e.g. aiida-core-base.

I guess it is quite explicitly documented here: https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/run_docker.html, I am not sure what to add.

**Comment by yakutovicha** [comment] 2022-08-02 15:36
@ljbeal what concerns your use case, I would propose the following:

1. Enter your current "production" container and export the aiida database (`verdi archive create ...`)
2. Copy the export file to the host machine, see [here](https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB0383441)
3. Launch an empty container with a properly mounted folder.
    3.1. Either the aiida-core container [1]
    3.2 Or by using the aiidalab-launch tool [2]
4. Import the export file from inside the new container.

[1]   `docker run -d --name aiida-container -v /home/beal/aiida-folder:/home/aiida aiidateam/aiida-core:1.6.8`
[2] https://aiidalab.readthedocs.io/en/latest/usage/index.html#aiidalab-launch

[UPDATE] There is a new 1.6.9 image of aiida-core. Better use it instead of 1.6.8, as it would be easier to switch to aiida-core:2.x

**Comment by yakutovicha** [comment] 2022-08-02 15:51
> > The PostgreSQL database folder is inside the user's home directory. That is – like any other directory – part of the container unless you mount it externally. Why would that be any slower compared to a dedicated volume?
> 
> As far as I understand, the default container uses an overlay filesystem with copy-on-write, that can be thus slow for IO intensive operations (I don't have benchmarks, but I remember at least one case where not mounting/using a volume was making a big difference). I'm not sure of the overheads of bind mounts and/or volumes (that seem to be also host-OS specific from a quick google search).

We should definitely test this.

**Comment by yakutovicha** [comment] 2022-08-07 22:10
> I don't have benchmarks, but I remember at least one case where not mounting/using a volume was making a big difference

I just tested it on my Mac, and the outcome is completely the opposite. Mounting a folder makes data copy 2x slower:

**Mounted folder:** (slowest)
```bash
(base) aiida@cf1c4cddff44:~$ dd if=/dev/zero of=/home/aiida/test111.img  bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 6.02865 s, 178 MB/s
(base) aiida@cf1c4cddff44:~$ dd if=/dev/zero of=/home/aiida/test222.img  bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 5.29225 s, 203 MB/s
(base) aiida@cf1c4cddff44:~$ dd if=/dev/zero of=/home/aiida/test333.img  bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 5.25267 s, 204 MB/s

Just to prove that the folder was actually mounted:

(base) aiida@cf1c4cddff44:~$ touch mounted_folder
(base) aiida@cf1c4cddff44:~$ ls
mounted_folder  test111.img  test222.img  test333.img
(base) aiida@cf1c4cddff44:~$
exit
(base) Aliaksandrs-MacBook-Pro:test-aiida-prerequisites yakutovicha$ ls
mounted_folder	test111.img  test222.img  test333.img
```

**No folder mount:**
```bash
(base) aiida@ee65e1be4723:~$ dd if=/dev/zero of=/home/aiida/test111.img  bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.13853 s, 502 MB/s
(base) aiida@ee65e1be4723:~$ dd if=/dev/zero of=/home/aiida/test222.img  bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.00057 s, 537 MB/s
(base) aiida@ee65e1be4723:~$ dd if=/dev/zero of=/home/aiida/test333.img  bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.50575 s, 429 MB/s
```

**Host system:** (fastest)
```bash
base) Aliaksandrs-MacBook-Pro:test-aiida-prerequisites yakutovicha$ dd if=/dev/zero of=/Users/yakutovicha/test-aiida-prerequisites/test555.img  bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.25026 s, 859 MB/s
```

Unless there are other open questions, I think we should close the issue.

**Comment by ljbeal** [comment] 2022-08-08 15:12
Thanks for the responses, there is some very useful information here. As this slowdown issue affects the actual archive creation (making full common-workflow group exports impossible), it makes experimentation in this regard rather difficult.

The solution I proposed was to simply export in chunks, a small test export functioned just fine, so it is merely a matter of finding the optimal chunk size. As such, I don't feel comfortable experimenting with the container that is currently running, as there is a very real possibility of data loss. Though of course, it can be done after submission (and the chunked export is completed)

I don't think I have any further questions to raise here, so the issue can be closed as far as I am concerned. The previous EoS submission is close to the final version, so I shall being experimenting with the exports soon. Once this is done I will try find the time to reproduce your results. we do have _a_ folder mounted currently, it is just not the home directory.

As for what to change with the documentation: You are correct, it is mentioned rather clearly on the linked page. The issue for myself was I was working with pre-existing containers, and was attempting to fix a number of bugs. So somewhere in the container switching this likely got lost (or never existed, hard to tell!). So no issue on your end, just user error!

Best regards,
Louis

**Comment by csadorf** [comment] 2022-08-08 16:21
Thanks for reporting back!

**Closed as completed by csadorf** 2022-08-08 16:21 UTC
